apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: aboakgko2-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/aboakgko2-java-springboot-gitops